version: 2.1

notify:
  webhooks:
    - url: https://d2506ce0.ngrok.io

executors:
  node:
    docker:
      - image: circleci/node:8.11-stretch-browsers

jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: exit 0

workflows:
  test-and-deploy:
    jobs:
      - build
