version: 2.1

setup: true

orbs:
  continuation: sandbox/continuation@0.0.1


jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - continuation/continue:
          configuration_path: generated-config.yml


workflows:
  test-and-deploy:
    jobs:
      - build
