version: 2

notify:
  webhooks:
    - url: http://2a69cf19.ngrok.io

jobs:
  build:
    docker:
      - image: circleci/node:8.11-stretch-browsers
    steps:
      - checkout
      - run: exit 0

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - build
