version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: exit 0
  test:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout
      - run: exit 0

workflows:
  test-and-deploy:
    jobs:
      - build
      - test
